# -*- coding: utf-8 -*-
"""id3_tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BD6jL5S8v81-ieqAcBAo5a74xQ8oXH9r
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn import tree
import matplotlib.pyplot as plt

data = {
    'Outlook': ['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny','Sunny','Rain','Sunny','Overcast','Overcast','Rain'],
    'Temperature': ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild'],
    'Humidity': ['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High'],
    'Wind': ['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Strong'],
    'PlayTennis': ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']
}

df = pd.DataFrame(data)
df

le = LabelEncoder()

for column in df.columns:
    df[column] = le.fit_transform(df[column])

df

X = df.drop('PlayTennis', axis=1)
y = df['PlayTennis']

model = DecisionTreeClassifier(criterion="entropy")
model.fit(X, y)

plt.figure(figsize=(12,8))
tree.plot_tree(model, feature_names=X.columns, class_names=["No","Yes"], filled=True)
plt.show()

sample = [[2,0,0,1]]   # example encoded values
prediction = model.predict(sample)

if prediction[0] == 1:
    print("Play Tennis: YES")
else:
    print("Play Tennis: NO")