# -*- coding: utf-8 -*-
"""logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0jDRBHP5iKx6gpVxogoEVBBHyJadLTz
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("HR_comma_sep.csv")

# Preview
print(df.head())
print(df.info())

print(df.describe())

print(df['left'].value_counts())
sns.countplot(x='left', data=df)
plt.title("Employee Retention Count (0 = Stayed, 1 = Left)")
plt.show()

corr = df.corr(numeric_only=True)
plt.figure(figsize=(10,6))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

salary_retention = df.groupby('salary')['left'].mean()

salary_retention.plot(kind='bar')
plt.title("Impact of Salary on Employee Retention")
plt.ylabel("Probability of Leaving")
plt.show()

dept_retention = df.groupby('Department')['left'].mean()

dept_retention.plot(kind='bar', figsize=(10,5))
plt.title("Department vs Employee Retention")
plt.ylabel("Probability of Leaving")
plt.xticks(rotation=45)
plt.show()

# One-hot encoding
df = pd.get_dummies(df, columns=['salary', 'Department'], drop_first=True)

X = df.drop('left', axis=1)
y = df['left']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))