# -*- coding: utf-8 -*-
"""regression_cart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FePElhvFLBQzi0s5FXIiZDBT0TrigwZU
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn import tree
import matplotlib.pyplot as plt

data = {
    "Hours": [1,2,3,4,5,6,7,8,9,10],
    "Score": [40,45,50,55,60,65,70,80,85,90]
}

df = pd.DataFrame(data)

X = df[["Hours"]]
y = df["Score"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = DecisionTreeRegressor(criterion="squared_error")
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Predicted values:", y_pred)

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

plt.figure(figsize=(10,6))
tree.plot_tree(model, feature_names=["Hours"], filled=True)
plt.show()

new_sample = [[7]]
prediction = model.predict(new_sample)

print("Predicted Score:", prediction[0])