# -*- coding: utf-8 -*-
"""Support_vector_machine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdWwXrDfUKHtX80-6vG9QI0hTTljNGyb
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

X = np.array([
    [1, 60, 50],
    [2, 65, 55],
    [3, 70, 60],
    [4, 75, 65],
    [5, 80, 70],
    [6, 85, 75],
    [7, 90, 80],
    [8, 95, 85],
    [2, 50, 45],
    [3, 55, 50],
    [4, 60, 55],
    [5, 65, 60],
    [6, 70, 65],
    [7, 75, 70],
    [8, 80, 75],
    [9, 85, 80]
])

y = np.array([
    0,0,0,1,1,1,1,1,
    0,0,0,1,1,1,1,1
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = SVC(kernel='linear')   # try 'rbf' also
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

new_student = np.array([[5, 70, 65]])  # example input
new_student = scaler.transform(new_student)

prediction = model.predict(new_student)

if prediction[0] == 1:
    print("\nResult: Pass")
else:
    print("\nResult: Fail")